Kong/public-shared-renovate

- kong-frontend-config.json
Ref: https://github.com/renovatebot/renovate/issues/23326
Renovate renamed "config:base" to "config:recommended" and this silently broke.
> fix: replace "config:base" with "config:recommended"

- kong-frontend-config.json
Even with `@kong` scoped dependencies, we still do not want to automatically upgrade to a new major version release.
> fix(fe): block automated major versions

- kong-frontend-config.json
Splitting apart the `@kong`, `@kong-ui`, and `@kong-ui-public` scoped dependency updates to provide a little more flexibility on merges.
When everything is grouped together, a single issue in one of the `@kong` SDK clients can block all of the other dependency updates. We'd like to split them apart in a more meaningful way.
[Here's an example of a large update PR](https://github.com/Kong/konnect-ui-apps/pull/2171)
> fix: split up kong dep groups

- kong-frontend-config.json
Ignore `inquierer` for FE repos so we don't need to rebuild the CI flows right now
> chore: ignore inquierer

- kong-frontend-config.json
Fix pattern matches that were no longer valid after switching to `matchPackageNames`
> fix: pattern matches

- kong-frontend-config.json
Group any `eslint` related dependencies and increase the minimum age by 2 days.
Using a broad match to cover things like:
```
@nuxt/eslint
eslint
vite-plugin-eslint2
eslint-config-kong-ui
```
> feat: group eslint dependencies

- kong-frontend-config.json
Previously, patch and minor version updates for Github actions would never match the "all non-major dependencies with stable version" grouping because Github action versions are prefixed with a "v". This change adds a new group that is specific to github actions that expects tags to be prefixed with a "v" (i.e. "v1.0.0").
> fix(github-actions): automerge all non-major github actions with stable version

- go.json
Removed `gomodMassage` from `postUpdateOptions` in `go.json` because it caused issues by creating unnecessary "require" blocks in `go.mod`. Instead of adding new dependencies to existing blocks, it sometimes created separate blocks like:
```go
require (
cel.dev/expr v0.16.1 // indirect
filippo.io/edwards25519 v1.1.0 // indirect
)
require (
NEW_DEP v0.0.1 // indirect
)
```
Added `gomodUpdateImportPaths` to `postUpdateOptions` to ensure Renovate updates import paths in source code for non-major releases, making dependency updates more seamless.
> chore(renovate): adjust postUpdateOptions for Go modules

- github-actions.json
- Disabled digest updates since regular version updates already cover them. This prevents Renovate from trying to create duplicate PRs for digest and version updates
- Ensured commit and PR titles use the full package name for clarity
- Prevented lowercase conversion of package names to keep `Kong` correctly capitalized
- Standardized commit actions to use lowercase (`update`, `pin`, `replace`, `roll back`)
- Updated PR body table to show full package name and include a source code link
> fix(github-actions): improve package name handling and prevent duplicate digest updates

- backend.json
- github-actions.json
- Added "commitMessageAction" to backend.json for consistency
- Introduced a package rule using "from ... to ..." version notation
- Changed GitHub Actions commit message action from "update" to "bump"
- Ensures existing automations relying on dependabot-like messages remain functional
> feat(renovate): align commit messages with dependabot format for existing automations

- backend.json
- Changed Renovate schedule from every weekday to only Monday before 4am (UTC)
- Reduces frequency of Renovate PRs for easier dependency management
> chore(renovate): run backend preset only before 4am on Monday

- kong-frontend-config.json
Ignore `Kong/kong-api-tests` action for automated updates
> fix: ignore kong-api-tests

- backend.json
- Increased `prHourlyLimit` from 2 to 15
- With weekly scheduling, the previous limit (2 PRs/hour) caused Renovate to open only 2 PRs per week, despite appearing as an hourly limit
- This ensures all pending updates (up to 15) are processed each Monday
> chore(renovate): increase hourly PR limit to 15

- kong-frontend-config.json
Updating only one package sometimes results in broken types or styling.
> feat(analytics): group analytics package updates together

- github-actions.json
Fixes bad rule that disabled all digest updates. Digest-only pins (e.g. master) were not getting updates, which is incorrect.
```json
{
"autoReplaceStringTemplate": "{{depName}}/regctl-installer@{{#if newDigest}}{{newDigest}}{{#if newValue}} # {{newValue}}{{/if}}{{/if}}{{#unless newDigest}}{{newValue}}{{/unless}}",
"commitMessageTopic": "{{{depName}}} action",
"currentDigest": "ce5fd131e371ffcdd7508b478cb223b3511a9183",
"datasource": "github-tags",
"depName": "regclient/actions",
"depType": "action",
"packageName": "regclient/actions",
"replaceString": "regclient/actions/regctl-installer@ce5fd131e371ffcdd7508b478cb223b3511a9183",
"versioning": "docker",
"warnings": [],
"updates": [
{
"updateType": "digest",
"newDigest": "4d6888fcc4842c9630f60ebc91715a45dd9bd7a3",
"branchName": …
```
> fix(renovate): allow digest updates for actions pinned by digest only

- backend.json
- Remove `local>` prefix from extended configs as it's misleading and just refers to the same remote source (ref. https://docs.renovatebot.com/config-presets/#local-presets)
- Fix `commitMessageExtra` to always include 'from ... to ...' in PR titles:
- Before: `chore(deps): bump postgres to latest`, `chore(deps): bump redis to b3ad798`
- After:  `chore(deps): bump postgres from 81f32a8 to 6efd0df`, `chore(deps): bump redis from 9abic82a to 6efd0df`
- Remove redundant rule disabling `tj-actions/changed-files` (already disabled in github-actions preset which is explicitly imported by the backend preset):
- https://github.com/Kong/public-shared-renovate/blob/ab99c115ecba2067dbe7d70d2fab5e693dbe11b0/github-actions.json#L26-L34
- https://github.com/Kong/public-shared-renovate/blob/ab99c115ecba2 …
> fix(preset/backend): improve commit message formatting and remove redundant config

- backend.json
Update commitMessageTopic to add `:{{newValue}}` to the dependency name for digest updates when `currentValue` and `newValue` are equal and not empty (e.g., for static Docker tags). This helps distinguish updates to the same image used with different tags
Examples:
- Before:
```
chore(deps): bump gcr.io/distroless/base-nossl-debian12 from 1368c7b to 84c4a85
chore(deps): bump gcr.io/distroless/base-nossl-debian12 from 393a396 to 081a62d
```
- After:
```
chore(deps): bump gcr.io/distroless/base-nossl-debian12:debug from 1368c7b to 84c4a85
chore(deps): bump gcr.io/distroless/base-nossl-debian12:debug-nonroot from 393a396 to 081a62d
```
---
Tested on Kuma's fork:
> fix(preset/backend): include tag in commit message for digest updates with static tag

- CODEOWNERS
- makefile.json
We manage some tools in our Makefiles using version variables like `TOOL_NAME_VERSION`. These are not supported out of the box by Renovate, so updates to those tools have to be done manually. This PR adds a custom manager to automate those updates and reduce maintenance effort.
* Added a new `makefile.json` Renovate preset
* Configures a custom regex manager for files like `Makefile` or `*.mk`
* Requires each version line to be preceded by a `# renovate:` comment with:
* `datasource`, `depName`, and optionally `versioning` and `registryUrl`
```make
```
* Example:
```make
GH_CLI_VERSION ?= 2.42.1
```
To test regexp you can use: https://regex101.com/r/XR22PL/1
> feat(preset/renovate): add custom regex manager for Makefile-based tools

- github-actions.json
Renovate did not correctly detect versions for `Kong/public-shared-actions/**` when releases used the new tag format. This sometimes led to wrong upgrades, because the old fallback allowed plain `vX.Y.Z` tags without a sub-action name to override proper sub-action releases. For example, when `security-actions/sca@4.1.5` existed but the repo also had a top-level `v4.2.0`, Renovate tried to update `security-actions/sca` to `4.2.0`. This change fixes detection, removes the unsafe fallback, and aligns with Renovate’s current manager file pattern requirements.
- Updated `matchStrings` and `extractVersionTemplate` to correctly capture release tags with sub-action paths and optional `@` or `v` prefixes, covering all expected variants:
- `@a/b@1.2.3` (format used before)
- `c/d/e@4.5.6` (current …
> fix(github-actions): correct version extraction for public-shared-actions tags

- backend.json
- github-actions-changed-files.json
- github-actions.json
- go.json
- makefile.json
Several renovate presets needed cleanup and improvements. We were duplicating the disable rule for `tj-actions/changed-files` in multiple presets, which made it harder to maintain and less clear why this action is treated specially. Backend projects were also using a hardcoded manual schedule and an hourly PR limit that delayed updates by a full week when limits were hit. In addition, we still maintained a custom Makefile manager even though Renovate now provides an official one. Documentation in many presets was written as single-line strings, making them harder to read and understand.
- Created a dedicated `github-actions-changed-files.json` preset that disables automated updates for `tj-actions/changed-files`. This rule already existed but was duplicated in several presets. Now it is …
> feat(presets): add changed-files preset and adopt official makefile mgr

- github-actions.json
Workflows depending on `Kong/public-shared-actions` could break when Renovate updated old versions of sub-actions (< v4) to later ones. The releases existed, but their names and tag formats did not match what GitHub expected (e.g., `workflow-notification@4.0.1` instead of `v4.0.1`). This mismatch meant Renovate could generate updates pointing to tags that GitHub could not resolve, leaving critical workflows like Slack notifications at risk of silently failing. To prevent this, Renovate is now configured to enforce digest pinning and to automatically upgrade any sub-actions below v4 to v4+. With these changes, actions are always referenced by their commit SHA with an inline version comment, ensuring they resolve correctly regardless of tag format and keeping workflows secure and stable.
- …
> feat(github-actions): enforce digest pinning for public-shared-actions

- modules/kuma/go-control-plane.json
Upstream `github.com/envoyproxy/go-control-plane` introduced a potential deadlock in v0.12.0 (see https://github.com/envoyproxy/go-control-plane/issues/875). To avoid this issue, Kuma temporarily relies on the fork `github.com/kumahq/go-control-plane`, which publishes builds in the format `vX.Y.Z-kong-...`. These versions are used via replace directives in `go.mod`, but Renovate does not manage them correctly by default. Without a dedicated preset, updates could be inconsistent, harder to review, or skipped entirely. This preset ensures that all replace directives for `kumahq/go-control-plane` and related subpackages are managed in a consistent, automated way.
- Introduced a custom regex manager that matches `go.mod` replace directives for `github.com/kumahq/go-control-plane` and its …
> ci(renovate): add preset for kumahq/go-control-plane replacements

- backend.json
- go.json
The backend and Go Renovate presets needed cleanup to make them easier to use and keep them consistent with best practices. The backend preset used unpinned presets and had extra settings that added little value. The Go preset was missing clear explanation of its role and did not group common dependencies, which made reviews noisier. This PR fixes these issues.
- Pin `github-actions` and `go` presets to `#1.12.0` for consistency
- Make commit messages clearer for `Kong/public-shared-actions` updates
- Keep digest and version info but simplify how the extra message is built
- Remove the PR body override since it was not needed
- Update description to explain it is a base Go preset that should be extended
- Drop direct `:gomod` extend to keep it modular
- Add grouping for common …
> feat(*): update backend and go presets for clarity and reliability

- makefile.json
The `makefile.json` preset was already an alias forwarding to Renovate's official `customManagers:makefileVersions`. While it worked as intended, users had no clear indication that it was temporary. We want to give teams clear warnings so they know to migrate in time.
- Kept the preset as an alias to `customManagers:makefileVersions`  
- Updated the description to clarify it is a compatibility alias  
- Added `prBodyNotes` so Renovate PRs display a visible deprecation warning with instructions and a timeline for removal  
There is no change in functionality, but teams now get clear deprecation warnings in Renovate PRs, helping them plan migration to the official `customManagers:makefileVersions` preset before January 2026.
> chore(makefile): add deprecation warning to makefile preset alias

- scoped/kuma/commit-message-baseline.json
We want a single, predictable commit message style across Kuma repos. Current messages vary by dependency type and preset ordering, which can slow code review and cause confusion. This preset sets a baseline that projects can extend while keeping key details clear.
- Added a Renovate preset under `scoped/kuma/commit-message-baseline.json`
- Topic selection: Use the full `packageName` for `*/public-shared-actions/**`, and strip `go:` and `aqua:` prefixes for other dependencies
- Extra line: Render `from X to Y` for version and digest updates, handle pseudo versions and pinned digest cases
- Action mappings: `pin`, `pinDigest`, `replacement`, and `rollback` use consistent verbs
- Ordering guidance: Repos should add a final catch all rule with `matchDepNames: '*'` that sets commit fields and …
> feat(scoped): add Kuma commit-message baseline preset
